
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COS DIVIDE LOG LPAREN MINUS NUMBER PLUS POWER RPAREN SIN SQRT TAN TIMESexpr : expr PLUS term\n| expr MINUS termexpr : termterm : term TIMES factor\n| term DIVIDE factorterm : factorfactor : power POWER factorfactor : powerpower : atomatom : NUMBERatom : LPAREN expr RPARENatom : SIN LPAREN expr RPAREN\n| COS LPAREN expr RPAREN\n| TAN LPAREN expr RPAREN\n| LOG LPAREN expr RPAREN\n| SQRT LPAREN expr RPAREN'
    
_lr_action_items = {'NUMBER':([0,7,13,14,15,16,17,19,20,21,22,23,],[6,6,6,6,6,6,6,6,6,6,6,6,]),'LPAREN':([0,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,23,],[7,7,19,20,21,22,23,7,7,7,7,7,7,7,7,7,7,]),'SIN':([0,7,13,14,15,16,17,19,20,21,22,23,],[8,8,8,8,8,8,8,8,8,8,8,8,]),'COS':([0,7,13,14,15,16,17,19,20,21,22,23,],[9,9,9,9,9,9,9,9,9,9,9,9,]),'TAN':([0,7,13,14,15,16,17,19,20,21,22,23,],[10,10,10,10,10,10,10,10,10,10,10,10,]),'LOG':([0,7,13,14,15,16,17,19,20,21,22,23,],[11,11,11,11,11,11,11,11,11,11,11,11,]),'SQRT':([0,7,13,14,15,16,17,19,20,21,22,23,],[12,12,12,12,12,12,12,12,12,12,12,12,]),'$end':([1,2,3,4,5,6,24,25,26,27,28,29,35,36,37,38,39,],[0,-3,-6,-8,-9,-10,-1,-2,-4,-5,-7,-11,-12,-13,-14,-15,-16,]),'PLUS':([1,2,3,4,5,6,18,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[13,-3,-6,-8,-9,-10,13,-1,-2,-4,-5,-7,-11,13,13,13,13,13,-12,-13,-14,-15,-16,]),'MINUS':([1,2,3,4,5,6,18,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[14,-3,-6,-8,-9,-10,14,-1,-2,-4,-5,-7,-11,14,14,14,14,14,-12,-13,-14,-15,-16,]),'RPAREN':([2,3,4,5,6,18,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[-3,-6,-8,-9,-10,29,-1,-2,-4,-5,-7,-11,35,36,37,38,39,-12,-13,-14,-15,-16,]),'TIMES':([2,3,4,5,6,24,25,26,27,28,29,35,36,37,38,39,],[15,-6,-8,-9,-10,15,15,-4,-5,-7,-11,-12,-13,-14,-15,-16,]),'DIVIDE':([2,3,4,5,6,24,25,26,27,28,29,35,36,37,38,39,],[16,-6,-8,-9,-10,16,16,-4,-5,-7,-11,-12,-13,-14,-15,-16,]),'POWER':([4,5,6,29,35,36,37,38,39,],[17,-9,-10,-11,-12,-13,-14,-15,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,7,19,20,21,22,23,],[1,18,30,31,32,33,34,]),'term':([0,7,13,14,19,20,21,22,23,],[2,2,24,25,2,2,2,2,2,]),'factor':([0,7,13,14,15,16,17,19,20,21,22,23,],[3,3,3,3,26,27,28,3,3,3,3,3,]),'power':([0,7,13,14,15,16,17,19,20,21,22,23,],[4,4,4,4,4,4,4,4,4,4,4,4,]),'atom':([0,7,13,14,15,16,17,19,20,21,22,23,],[5,5,5,5,5,5,5,5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS term','expr',3,'p_expression','Scientific_calc.py',182),
  ('expr -> expr MINUS term','expr',3,'p_expression','Scientific_calc.py',183),
  ('expr -> term','expr',1,'p_expression_term','Scientific_calc.py',191),
  ('term -> term TIMES factor','term',3,'p_term_mult','Scientific_calc.py',196),
  ('term -> term DIVIDE factor','term',3,'p_term_mult','Scientific_calc.py',197),
  ('term -> factor','term',1,'p_term_factor','Scientific_calc.py',205),
  ('factor -> power POWER factor','factor',3,'p_factor_power','Scientific_calc.py',210),
  ('factor -> power','factor',1,'p_factor_atom','Scientific_calc.py',215),
  ('power -> atom','power',1,'p_power_atom','Scientific_calc.py',220),
  ('atom -> NUMBER','atom',1,'p_atom_number','Scientific_calc.py',225),
  ('atom -> LPAREN expr RPAREN','atom',3,'p_atom_paren','Scientific_calc.py',230),
  ('atom -> SIN LPAREN expr RPAREN','atom',4,'p_atom_function','Scientific_calc.py',235),
  ('atom -> COS LPAREN expr RPAREN','atom',4,'p_atom_function','Scientific_calc.py',236),
  ('atom -> TAN LPAREN expr RPAREN','atom',4,'p_atom_function','Scientific_calc.py',237),
  ('atom -> LOG LPAREN expr RPAREN','atom',4,'p_atom_function','Scientific_calc.py',238),
  ('atom -> SQRT LPAREN expr RPAREN','atom',4,'p_atom_function','Scientific_calc.py',239),
]
